### ISSUE TITLE
Make Studio compatible with g2p 2.0

### ISSUE THREAD

**Issue by joanise** [ReadAlongs/Studio#188]
If we just update pydantic to match g2p 2.0's requirements, the version of fastapi currently used by Studio has an import exception:

```
$ cd test
$ ./test_web_api.py
Traceback (most recent call last):
  File "C:\Users\joanise\sandboxes\Studio\test\run.py", line 39, in <module>
    from test_web_api import TestWebApi
  File "C:\Users\joanise\sandboxes\Studio\test\test_web_api.py", line 9, in <module>
    from fastapi.testclient import TestClient
  File "C:\Users\joanise\Miniconda3\envs\ras-py310\lib\site-packages\fastapi\__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "C:\Users\joanise\Miniconda3\envs\ras-py310\lib\site-packages\fastapi\applications.py", line 15, in <module>
    from fastapi import routing
  File "C:\Users\joanise\Miniconda3\envs\ras-py310\lib\site-packages\fastapi\routing.py", line 21, in <module>
    from fastapi import params
  File "C:\Users\joanise\Miniconda3\envs\ras-py310\lib\site-packages\fastapi\params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (C:\Users\joanise\Miniconda3\envs\ras-py310\lib\site-packages\pydantic\fields.py)
```

The first version of `fastapi` that is compatible with Pydantic 2 is 0.100.0.
With `pip install fastapi==0.100.0 httpx`
we now get errors where Pydantic validation is rejecting calls due to fields missing:

```
ERROR: test_assemble_from_plain_text (__main__.TestWebApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_web_api.py", line 35, in test_assemble_from_plain_text
    response = API_CLIENT.post("/api/v1/assemble", json=request)
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\starlette\testclient.py", line 590, in post
    return super().post(
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\httpx\_client.py", line 1132, in post
    return self.request(
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\starlette\testclient.py", line 465, in request
    return super().request(
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\httpx\_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\httpx\_client.py", line 901, in send
    response = self._send_handling_auth(
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\httpx\_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\httpx\_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\httpx\_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\starlette\testclient.py", line 342, in handle_request
    raise exc
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\starlette\testclient.py", line 339, in handle_request
    portal.call(self.app, scope, receive, send)
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\anyio\from_thread.py", line 277, in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\concurrent\futures\_base.py", line 444, in result
    return self.__get_result()
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\anyio\from_thread.py", line 217, in _call_func
    retval = await retval
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\fastapi\applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\starlette\routing.py", line 443, in handle    await self.app(scope, receive, send)
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\fastapi\applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\starlette\routing.py", line 276, in handle    await self.app(scope, receive, send)
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\fastapi\routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\fastapi\routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "c:\users\joanise\sandboxes\studio\readalongs\web_api.py", line 247, in assemble
    response = AssembleResponse(
  File "C:\Users\joanise\Miniconda3\envs\ras-py38\lib\site-packages\pydantic\main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 3 validation errors for AssembleResponse
parsed
  Field required [type=missing, input_value={'lexicon': [('t0b0d0p0s0... present; tokenizing\n'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
tokenized
  Field required [type=missing, input_value={'lexicon': [('t0b0d0p0s0... present; tokenizing\n'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
g2ped
  Field required [type=missing, input_value={'lexicon': [('t0b0d0p0s0... present; tokenizing\n'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
```

**Comment by joanise** [comment]
Working on it, almost fixed. The issue is that Pydantic 2 wants default declared when a field is optional. Making a field optional no longer implicitly makes its default value None.

**Comment by joanise** [comment]
Thanks for the hint @dhdaines ! mypy told me most of the fixes I had to do to make things work, way easier!
