### ISSUE TITLE
Can't install on Python 3.12, Ubuntu 22.04 due to broken editdistance package

### ISSUE THREAD

**Issue by dhdaines** [ReadAlongs/Studio#200]
The "editdistance" package does not seem to install properly on Python 3.12 for me.  Not our problem, I know, but we might have to find an alternative package.  Log:

```
  Downloading editdistance-0.6.2.tar.gz (31 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "/home/dhd/work/ReadAlongs/ve312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/dhd/work/ReadAlongs/ve312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/dhd/work/ReadAlongs/ve312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-phpbupwd/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-phpbupwd/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-phpbupwd/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 25, in <module>
        File "/tmp/pip-build-env-phpbupwd/overlay/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1010, in cythonize
          module_list, module_metadata = create_extension_list(
                                         ^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-phpbupwd/overlay/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 845, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "/tmp/pip-build-env-phpbupwd/overlay/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 117, in nonempty
          raise ValueError(error_msg)
      ValueError: 'editdistance/bycython.pyx' doesn't match any files
      [end of output]

```

**Comment by dhdaines** [comment]
Seems to actually be this problem: https://github.com/roy-ht/editdistance/issues/105

We should be able to get around it by installing from the Git repository instead of the broken source distribution.

**Comment by roedoejet** [comment]
The problem with installing from a git repo is that pypi doesn't let you publish packages with git requirements anymore I don't think

**Comment by roedoejet** [comment]
And this is a requirement from panphon which is pretty core for g2p and readalongs.

**Comment by dhdaines** [comment]
> And this is a requirement from panphon which is pretty core for g2p and readalongs.

Hmm, that's not good ... not much we can do about it in that case since it's not our dependency.
