### ISSUE TITLE
Error message for incorrect argument ordering

### ISSUE THREAD

**Issue by roedoejet** [ReadAlongs/Studio#22]
If you accidentally provide an audio file as the first argument to `readalongs align` and a text file after, it tries to read the mp3 file as a text file and gives the following error:

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 45: invalid start byte`

We should handle this differently.

**Comment by joanise** [comment]
This error still occurs. E.g.:

```
$ readalongs align -l fra data/ej-fra.m4a data/ej-fra.txt delme -f
Traceback (most recent call last):
  File "C:\Users\joanise\RAS\ras-env\Scripts\readalongs-script.py", line 11, in <module>
    load_entry_point('readalongs', 'console_scripts', 'readalongs')()
  File "c:\users\joanise\ras\ras-env\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\joanise\ras\ras-env\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "c:\users\joanise\ras\ras-env\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\joanise\ras\ras-env\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\joanise\ras\ras-env\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\joanise\ras\studio\readalongs\cli.py", line 343, in align
    save_temps=temp_base,
  File "c:\users\joanise\ras\studio\readalongs\align.py", line 808, in create_input_tei
    text = f.readlines()
  File "C:\Users\joanise\AppData\Local\Programs\Python\Python37\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 35: invalid start byte
```
