### ISSUE TITLE
EPub not working

### ISSUE THREAD

**Issue by roedoejet** [ReadAlongs/Studio#42]
After aligning and then running `readalongs epub output.smil output.epub`, I try to read the epub file using calibre (v3.39.1) and get the following error:

```
calibre, version 3.39.1
ERROR: Could not open e-book: Failed to read book, /Users/pinea/Calibre Library/Unknown/output (5)/output - Unknown.epub click "Show Details" for more information

Traceback (most recent call last):
  File "site-packages/calibre/utils/ipc/simple_worker.py", line 289, in main
  File "site-packages/calibre/ebooks/oeb/iterator/book.py", line 65, in extract_book
  File "site-packages/calibre/customize/conversion.py", line 244, in __call__
  File "site-packages/calibre/ebooks/conversion/plugins/epub_input.py", line 344, in convert
ValueError: No valid entries in the spine of this EPUB
```

**Comment by dhdaines** [comment]
yup ... this is a TODO for me for months and months now! I will assign it to myself

**Comment by roedoejet** [comment]
Removed for now in https://github.com/ReadAlongs/Studio/pull/90
