### ISSUE TITLE
Question on usage

### ISSUE THREAD

**Issue by gelsas** [ReadAlongs/Studio#66]
Hi,

I am currently looking for a way/solution to be able to read a-long my ebooks.
I have an audiobook for each of my ebooks. 

My question now is, (since I am not a programmer myself and I am not sure if I understand this correctly) can this software be used to basically create a "whisper sync" like feature, to be able to read a-long in the same way?

best,
gelsas

**Comment by joanise** [comment]
Hi Gelsas,
Thanks for reaching out. What you're describing should be possible with this technology, but at the moment the project is at a stage where it takes a fair amount of technical knowledge to use. Our goal is that it will eventually be easy for anyone to use, but we're not there yet.
So yes, given an audio file and a text transcript of it, we're usually* able to produce an alignment that indicates when each word occurs in the audio. The result can be displayed using our own web component, or converted to ELAN or ePub or HTML, or to whatever format you need if you have the technical knowledge to do it.
Cheers,
Eric
*I say "usually" because the engine does its best effort, but does not always succeed in finding an alignment, and sometimes has mistakes in the alignment it does find.

**Comment by gelsas** [comment]
Is there a YouTube video or something like that which guides me through the process of setting everything up and trying it with one of my ebooks and audiobooks myself ?
(What input format does this software need ?)

**Comment by gelsas** [comment]
I have just created the docker container with the command from the readme on my Qnap NAS but I am unable to access the web interface. I only get this message displayed: ERR_CONNECTION_REFUSED

**Comment by gelsas** [comment]
I have just got everything running in docker and I am able to access the web app via port 5000. 

From what I understood I can now generate upload text and mp3 and generate the files via the web app.

How can I now install the web component to use the generated files ?

**Comment by gelsas** [comment]
Just tried to use the web app but I am getting this error:

`ERROR - Exception on /step/3 [GET]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
Traceback (most recent call last):                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2070, in wsgi_app                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
    response = self.full_dispatch_request()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1515, in full_dispatch_request                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
    rv = self.handle_user_exception(e)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1513, in full_dispatch_request                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
    rv = self.dispatch_request()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1499, in dispatch_request                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
  File "/opt/readalong-studio/readalongs/views.py", line 243, in steps                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
    return render_template("export.html", data=data)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
UnboundLocalError: local variable 'data' referenced before assignment                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
[2021-07-27 23:32:04 +0000] [662] [ERROR] Error handling request /socket.io/?EIO=3&transport=websocket&sid=07a5d5e1322b48d7b1ac999ea58400c0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
Traceback (most recent call last):                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/base_async.py", line 55, in handle                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
    self.handle_request(listener_name, req, client, addr)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/ggevent.py", line 127, in handle_request                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
    super().handle_request(listener_name, req, sock, addr)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/base_async.py", line 117, in handle_request                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
    resp.close()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/http/wsgi.py", line 391, in close                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    self.send_headers()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/http/wsgi.py", line 318, in send_headers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
    tosend = self.default_headers()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/http/wsgi.py", line 299, in default_headers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    elif self.should_close():                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/http/wsgi.py", line 219, in should_close                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
    if self.status_code < 200 or self.status_code in (204, 304):                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
AttributeError: 'Response' object has no attribute 'status_code'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
Traceback (most recent call last):                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
  File "/usr/local/lib/python3.7/dist-packages/eventlet/hubs/hub.py", line 476, in fire_timers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
    timer()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
  File "/usr/local/lib/python3.7/dist-packages/eventlet/hubs/timer.py", line 59, in __call__                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
    cb(*args, **kw)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
  File "/usr/local/lib/python3.7/dist-packages/eventlet/semaphore.py", line 152, in _do_acquire                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
    waiter.switch()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
  File "src/gevent/greenlet.py", line 910, in gevent._gevent_cgreenlet.Greenlet.run                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
  File "src/gevent/greenlet.py", line 875, in gevent._gevent_cgreenlet.Greenlet._Greenlet__report_result                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
  File "src/gevent/_gevent_cgreenlet.pxd", line 45, in gevent._gevent_cgreenlet.get_my_hub                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
TypeError: Cannot convert greenlet.greenlet to gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop                      `

**Comment by joanise** [comment]
Hi @gelsas,

User documentation like you're asking for is high on our project's priority list! There isn't yet. Our target is to have the ease of use you need by March 2021.

I'm not sure you'll be able to get to completion on your project right now, but I'll give you some broad lines. The first major issue is that the GUI is in need of a major remake! Current successful creation of readalongs is all done using the command line interface instead. For now, the best source of information about the CLI is https://github.com/finguist/ReadAlong-Studio-Documentation/blob/main/prepare.md, which I'm planning to merge back into this repo within a month or two.

The second major issue is that we don't accept full-format files. The errors you're seeing are because the input text format is limited to plain text (the kind you get in Notepad) with an empty line marking a paragraph boundary, and two consecutive empty lines marking a page break. The test text files in https://github.com/ReadAlongs/Studio/tree/master/test/data show some examples - look at `fra.txt` and `ej-fra.txt`.

The only XML format we accept is the format produced by `readalongs prepare` from a plain text file as described above.

Accepting fully formatted text file formats like Word is not on our roadmap right now, it would be a lot of coding work. Conversion to plain text has to be done mostly manually.

So, I suggest you have a look at https://github.com/finguist/ReadAlong-Studio-Documentation/blob/main/prepare.md and keep in mind you are taking on a pretty big project using our tool in its current state. I'll be happy to assist further if I can, though not necessarily quickly, as you can see.
